import 'package:flutter/material.dart';
import '../../../core/utils/validators.dart';
import '../../../core/widgets/app_button.dart';
import '../../../core/widgets/app_text_field.dart';
import '../domain/flat.dart';
import '../domain/floor.dart';
import '../domain/tower.dart';

class FlatAutogenerateDialog extends StatefulWidget {
  final String societyId;
  final List<Tower> towers;
  final List<Floor> floors;
  final String? initialTowerId;

  const FlatAutogenerateDialog({
    super.key,
    required this.societyId,
    required this.towers,
    required this.floors,
    this.initialTowerId,
  });

  static Future<List<Flat>?> show(
    BuildContext context, {
    required String societyId,
    required List<Tower> towers,
    required List<Floor> floors,
    String? initialTowerId,
  }) {
    return showDialog<List<Flat>>(
      context: context,
      barrierDismissible: false,
      builder: (context) => FlatAutogenerateDialog(
        societyId: societyId,
        towers: towers,
        floors: floors,
        initialTowerId: initialTowerId,
      ),
    );
  }

  @override
  State<FlatAutogenerateDialog> createState() => _FlatAutogenerateDialogState();
}

class _FlatAutogenerateDialogState extends State<FlatAutogenerateDialog> {
  final _formKey = GlobalKey<FormState>();
  late String? _selectedTowerId;
  String? _selectedFloorId; // null means 'All Floors'
  late TextEditingController _flatsPerFloorController;
  late TextEditingController _prefixController;
  late TextEditingController _areaController;
  FlatType _flatType = FlatType.twoBhk;

  @override
  void initState() {
    super.initState();
    _selectedTowerId = widget.initialTowerId ??
        (widget.towers.isNotEmpty ? widget.towers.first.id : null);
    _flatsPerFloorController = TextEditingController(text: '3');
    _prefixController = TextEditingController();
    _areaController = TextEditingController();

    _updatePrefixForTower(_selectedTowerId);
  }

  void _updatePrefixForTower(String? towerId) {
    if (towerId == null) return;
    final tower = widget.towers.firstWhere((t) => t.id == towerId, orElse: () => widget.towers.first);
    final parts = tower.name.trim().split(RegExp(r'\s+'));
    final last = parts.last;
    if (last.length <= 2) {
      _prefixController.text = '${last.toUpperCase()}-';
    } else {
      _prefixController.text = '${tower.name[0].toUpperCase()}-';
    }
  }

  @override
  void dispose() {
    _flatsPerFloorController.dispose();
    _prefixController.dispose();
    _areaController.dispose();
    super.dispose();
  }

  List<Floor> _getFloorsForTower(String? towerId) {
    if (towerId == null) return [];
    return widget.floors.where((f) => f.towerId == towerId).toList()
      ..sort((a, b) => a.floorNumber.compareTo(b.floorNumber));
  }

  List<Floor> _getTargetFloors() {
    final available = _getFloorsForTower(_selectedTowerId);
    if (_selectedFloorId == null || _selectedFloorId!.isEmpty) {
      return available;
    }
    return available.where((f) => f.id == _selectedFloorId).toList();
  }

  List<String> _getPreviewFlatNumbers() {
    final floors = _getTargetFloors();
    final count = int.tryParse(_flatsPerFloorController.text.trim()) ?? 0;
    if (floors.isEmpty || count <= 0) return [];

    final prefix = _prefixController.text.trim();
    final list = <String>[];
    for (final floor in floors) {
      for (int i = 1; i <= count; i++) {
        list.add('$prefix${floor.floorNumber * 100 + i}');
      }
    }
    return list;
  }

  void _submit() {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedTowerId == null) return;

    final targetFloors = _getTargetFloors();
    if (targetFloors.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No floors available in selected tower.')),
      );
      return;
    }

    final count = int.tryParse(_flatsPerFloorController.text.trim()) ?? 3;
    final prefix = _prefixController.text.trim();
    final areaText = _areaController.text.trim();
    final area = areaText.isNotEmpty ? (double.tryParse(areaText) ?? 0.0) : 0.0;
    final now = DateTime.now();

    final flats = <Flat>[];
    for (final floor in targetFloors) {
      for (int i = 1; i <= count; i++) {
        final flatNum = '$prefix${floor.floorNumber * 100 + i}';
        flats.add(Flat(
          id: 'flt-${now.millisecondsSinceEpoch}-${floor.id}-$i',
          societyId: widget.societyId,
          towerId: _selectedTowerId!,
          floorId: floor.id,
          flatNumber: flatNum,
          flatType: _flatType,
          areaSqFt: area,
          occupancyStatus: OccupancyStatus.vacant,
          createdAt: now.add(Duration(milliseconds: floor.floorNumber * 10 + i)),
        ));
      }
    }

    Navigator.of(context).pop(flats);
  }

  @override
  Widget build(BuildContext context) {
    final availableFloors = _getFloorsForTower(_selectedTowerId);
    final targetFloors = _getTargetFloors();
    final count = int.tryParse(_flatsPerFloorController.text.trim()) ?? 0;
    final totalToGenerate = targetFloors.length * count;
    final previewList = _getPreviewFlatNumbers();
    final dialogWidth = (MediaQuery.sizeOf(context).width - 48).clamp(340.0, 500.0);

    return AlertDialog(
      title: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(
              Icons.auto_awesome,
              color: Theme.of(context).colorScheme.primary,
              size: 22,
            ),
          ),
          const SizedBox(width: 12),
          const Expanded(
            child: Text('Auto-Generate Flats'),
          ),
        ],
      ),
      content: SizedBox(
        width: dialogWidth,
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Tower Picker
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Target Tower', style: Theme.of(context).textTheme.labelMedium),
                    const SizedBox(height: 6),
                    DropdownButtonFormField<String>(
                      value: _selectedTowerId,
                      decoration: const InputDecoration(
                        contentPadding: EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                      ),
                      items: widget.towers.map((t) {
                        return DropdownMenuItem(value: t.id, child: Text(t.name));
                      }).toList(),
                      onChanged: (val) {
                        if (val != null) {
                          setState(() {
                            _selectedTowerId = val;
                            _selectedFloorId = null;
                            _updatePrefixForTower(val);
                          });
                        }
                      },
                    ),
                  ],
                ),
                const SizedBox(height: 14),

                // Floor Scope Picker
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Floor Scope', style: Theme.of(context).textTheme.labelMedium),
                    const SizedBox(height: 6),
                    DropdownButtonFormField<String?>(
                      value: _selectedFloorId,
                      decoration: const InputDecoration(
                        contentPadding: EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                      ),
                      items: [
                        DropdownMenuItem<String?>(
                          value: null,
                          child: Text('All Floors in Tower (${availableFloors.length} floors)'),
                        ),
                        ...availableFloors.map((f) {
                          return DropdownMenuItem<String?>(
                            value: f.id,
                            child: Text(f.displayName),
                          );
                        }),
                      ],
                      onChanged: (val) {
                        setState(() {
                          _selectedFloorId = val;
                        });
                      },
                    ),
                  ],
                ),
                const SizedBox(height: 14),

                // Flats per floor & Flat Type
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: AppTextField(
                        key: const Key('autogen_flats_per_floor'),
                        controller: _flatsPerFloorController,
                        label: 'Flats Per Floor',
                        hint: 'e.g. 3',
                        keyboardType: TextInputType.number,
                        validator: (val) => Validators.positiveInt(val, 'Flats count'),
                        onChanged: (_) => setState(() {}),
                      ),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Flat Type', style: Theme.of(context).textTheme.labelMedium),
                          const SizedBox(height: 6),
                          DropdownButtonFormField<FlatType>(
                            value: _flatType,
                            decoration: const InputDecoration(
                              contentPadding: EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                            ),
                            items: FlatType.values.map((t) {
                              return DropdownMenuItem(value: t, child: Text(t.displayName));
                            }).toList(),
                            onChanged: (val) {
                              if (val != null) setState(() => _flatType = val);
                            },
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 14),

                // Numbering Prefix & Optional Area
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: AppTextField(
                        key: const Key('autogen_prefix_field'),
                        controller: _prefixController,
                        label: 'Prefix (Optional)',
                        hint: 'e.g. A-',
                        onChanged: (_) => setState(() {}),
                      ),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: AppTextField(
                        key: const Key('autogen_area_field'),
                        controller: _areaController,
                        label: 'Area (sq. ft.) (Optional)',
                        hint: 'e.g. 1150',
                        keyboardType: TextInputType.number,
                        validator: (val) => Validators.optionalPositiveDouble(val, 'Area'),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Generation Preview Banner
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.06),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.2),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            'Summary Preview',
                            style: Theme.of(context).textTheme.labelMedium?.copyWith(
                                  fontWeight: FontWeight.bold,
                                ),
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                            decoration: BoxDecoration(
                              color: Theme.of(context).colorScheme.primary,
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: Text(
                              '$totalToGenerate Flats Total',
                              style: const TextStyle(
                                color: Colors.white,
                                fontSize: 11,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      if (previewList.isEmpty)
                        Text(
                          'No flats will be generated. Check your floor and count settings.',
                          style: Theme.of(context).textTheme.bodySmall,
                        )
                      else ...[
                        Wrap(
                          spacing: 6,
                          runSpacing: 4,
                          children: [
                            ...previewList.take(8).map((flatNo) => Chip(
                                  label: Text(flatNo, style: const TextStyle(fontSize: 11)),
                                  visualDensity: VisualDensity.compact,
                                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                  padding: EdgeInsets.zero,
                                )),
                            if (previewList.length > 8)
                              Padding(
                                padding: const EdgeInsets.only(top: 6),
                                child: Text(
                                  '+${previewList.length - 8} more',
                                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                        fontWeight: FontWeight.w600,
                                        color: Theme.of(context).colorScheme.primary,
                                      ),
                                ),
                              ),
                          ],
                        ),
                      ],
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
      actionsPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      actions: [
        AppButton(
          text: 'Cancel',
          variant: AppButtonVariant.text,
          onPressed: () => Navigator.of(context).pop(),
        ),
        AppButton(
          key: const Key('autogen_submit_button'),
          text: 'Generate $totalToGenerate Flats',
          icon: Icons.auto_awesome,
          onPressed: totalToGenerate > 0 ? _submit : null,
        ),
      ],
    );
  }
}
